title: Scratux
theme: jekyll-theme-architect
show_downloads: true
github:
  deb_url: https://github.com/scratux/scratux/releases/download/v1.0.1/scratux_1.0.1_amd64.deb
  appimage_url: https://github.com/scratux/scratux/releases/download/v1.0.1/scratux.1.0.1.AppImage
  arch_url: https://github.com/scratux/scratux/releases/download/v1.0.1/scratux-1.0.1.pacman
  version: 1.0.1
