title: Scratux
description: Free and open source Linux Binaries of Scratch Desktop. Scratux is a block-based visual programming language targeted primarily at children
github:
  deb_url: https://github.com/scratux/scratux/releases/download/1.4.1/scratux_1.4.1_amd64.deb
  rpm_url: https://github.com/scratux/scratux/releases/download/1.4.1/scratux-1.4.1.x86_64.rpm
  appimage_url: https://github.com/scratux/scratux/releases/download/1.4.1/scratux-1.4.1.AppImage
  arch_url: https://github.com/scratux/scratux/releases/download/1.4.1/scratux-1.4.1.pacman
  arm_url: https://github.com/scratux/scratux/releases/download/1.4.1/scratux_1.4.1_armv7l.deb
  version: 1.4.1
  scratchversion: 3.10.2
