title: Scratux
theme: jekyll-theme-architect
show_downloads: true
github:
  deb_url: https://github.com/scratux/scratux/releases/download/v1.0/scratux.1.0.0.AppImage.zip
  appimage_url: https://github.com/scratux/scratux/releases/download/v1.0/scratux_1.0.0_amd64.deb
  version: 1.0
